# Generated by Django 5.2.9 on 2025-12-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('fg_color', models.CharField(default='#000000', max_length=7)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('size', models.PositiveIntegerField(default=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
